/**
 * Stable, machine-readable error codes. Clients depend on these strings,
 * so renaming requires a versioned API change.
 */
export const ErrorCodes = {
  // Auth
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_REUSE_DETECTED: 'AUTH_REFRESH_REUSE_DETECTED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',
  AUTH_CSRF_HEADER_MISSING: 'AUTH_CSRF_HEADER_MISSING',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  AUTH_VERIFY_TOKEN_INVALID: 'AUTH_VERIFY_TOKEN_INVALID',

  // Authorisation
  FORBIDDEN: 'FORBIDDEN',
  RBAC_CAPABILITY_DENIED: 'RBAC_CAPABILITY_DENIED',
  TENANCY_VIOLATION: 'TENANCY_VIOLATION',

  // Tier / billing gate
  TIER_GATE: 'TIER_GATE',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RESOURCE_DUPLICATE: 'RESOURCE_DUPLICATE',
  RESOURCE_STATE_RACE: 'RESOURCE_STATE_RACE',

  // Quota / rate
  RATE_LIMITED: 'RATE_LIMITED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',

  // Internal / dependency
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  AI_BOTH_PROVIDERS_FAILED: 'AI_BOTH_PROVIDERS_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
